wx:
  appid: wx9c032fd7101a8c8f
#  appid: wxd29802dc33bb8d3a 公众号
  # daef2ddec7f8cae9e73a3f3c6a499db0 小程序
  secret: ae265f610fecb226e661d85f1f2efaa5
#  secret: 5421433393b1553c46cff1629d2e21af   测试公众号
#  openId: o7k-85871xRMa4BazeK3GtSCM5DA
  openId: o7k-854O0ohupuzW4JDA4YxHD9KA

weather:
  #生日 yyyy-mm-dd
  birthday: 1998-03-01
  #在一起的日子 yyyy-mm-dd
  love: 2022-03-10
  #阴历阳历
  chineseDate: true
  #模板ID
#  templateId: INyIgmSyBpSGc88rkyhBNJ2RPzB2IpYnqREcW0jjuqE
  templateId: PbMD79NYp4SyTYink4S5Zw0lcdJdUgbv-yXSi45TcKc